### ISSUE TITLE
Need help to fix pattern-cinnamon icon for breeze.

### ISSUE THREAD

**Issue by shenlebantongying** [yast/yast-theme#138]
I submitted the icon for cinnamon https://github.com/yast/yast-theme/pull/134. 

However, I only put it on hicolor folder. We want it to show on YaST with Breeze too.

I am not sure how to correctly create a symbolic link in this situation :(

Or we can just duplicate the file?

Pls help.

**Comment by shundhammer** [comment]
@hellcp should know more about this.

**Comment by hellcp** [comment]
Breeze inherits icons from itself first, and because `pattern` icon exists, that means that is the icon that's inherited first.

Honestly we probably should just rename icons to start with `yast-` so that's not an issue, but right now I'm afraid you will have to talk with breeze upstream

**Comment by hellcp** [comment]
Oh, right, our pattern icons for breeze are in this repo, I guess you just copy the file then

**Comment by ancorgs** [comment]
> Oh, right, our pattern icons for breeze are in this repo, I guess you just copy the file then

If I understood this correctly, a separate pull request to copy the same file to the other locations is pending here. Isn't it?

Or can we close this issue?

**Comment by hellcp** [comment]
Yup, it was fixed already

**Comment by shenlebantongying** [comment]
Yes, only need this PR to be merged https://github.com/yast/yast-theme/pull/143

**Comment by dgdavid** [comment]
Just for the record, if I'm not wrong the intention was fix it with #143 but finally it has been fixed in #148 and #149.
