### ISSUE TITLE
YaST icon is blurred in Task Switcher under KDE, openSUSE Tumbleweed

### ISSUE THREAD

**Issue by xuzhao9** [yast/yast-theme#76]
I am an openSUSE Tumbleweed user and I use Large Icons for KDE Task Switcher theme.
I found the icon of YaST looks like this. http://imgur.com/a/3ArgE
Seems YaST is using an 48x48 icon in the titlebar, could you please increase the size of the icon?

**Comment by shundhammer** [comment]
We are using SVG icons now (thanks to @hellcp who spent a lot of work to do that), so this should no longer be an issue. Please check with a recent TW.
